### PR TITLE
Modernize for current software.

### PR DESCRIPTION
**Pull request by oddluck**
This project was not working with the latest rails and various dependencies, now it does.

### CODE REVIEW

**Comment by sottenad** [comment]
There looks like a lot of good stuff in here, thank you. However it looks like parts of your React app are in the PR (babel and webpack and other deps as well)? Was this intentional?

**Comment by oddluck** [comment]
I pulled in some commits from other forks, among which there is a React frontend I haven't had time play with. It was intentional in that I might explore using it at some point and wanted to keep the additions. I can strip it out and make another pull request here if you want though.  Also, appreciate all the work you put into this, thank you.

**Comment by sottenad** [comment]
If you can remove all the front-end/build stuff you've got in here, and not delete any of the views I have in the solution, we can push these changes through. I do use this repo to deploy directly to jservice.io, so its important that the views are not changed/deleted.  Thanks for the effort to modernize the back end.

**Comment by oddluck** [comment]
Ok, closing this pull request and re-submitting with only the most basic changes.

**Pull request closed without merging**
